[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true



